# Generated by Django 2.1.4 on 2018-12-31 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
        migrations.AlterModelTable(
            name='email',
            table=None,
        ),
    ]
