# Generated by Django 2.2.4 on 2019-08-22 04:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgequest', '0002_auto_20181231_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('usevec', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=512)),
                ('docvec', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=300)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('usevec', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=512)),
                ('docvec', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=300)),
                ('replies', models.ManyToManyField(null=True, through='knowledgequest.Option', to='knowledgequest.Reply')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgequest.Reply'),
        ),
        migrations.AddField(
            model_name='option',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgequest.Statement'),
        ),
        migrations.AddField(
            model_name='participant',
            name='replies',
            field=models.ManyToManyField(blank=True, null=True, to='knowledgequest.Reply'),
        ),
        migrations.AddField(
            model_name='participant',
            name='statements',
            field=models.ManyToManyField(blank=True, null=True, to='knowledgequest.Statement'),
        ),
    ]
